#! /bin/sh

# load ICC profile
#pgrep -x xiccd > /dev/null || xiccd &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

pgrep -x feh > /dev/null || feh --randomize --bg-fill "$HOME/wallpapers/*" --no-fehbg

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a feh state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# load compositor
pgrep -x picom > /dev/null || picom &
# start polybar
. "$HOME/.config/polybar/launch.sh" nord

# start input method
pgrep -x uim-xim > /dev/null || uim-xim &
pgrep -x uim-toolbar-gtk3-systray > /dev/null || uim-toolbar-gtk3-systray &
# start notification daemon
#pgrep -x lxqt-notificationd > /dev/null || lxqt-notificationd &
pgrep -x /usr/lib/xfce4/notifyd/xfce4-notifyd > /dev/null || /usr/lib/xfce4/notifyd/xfce4-notifyd &
