# color scheme settings {{{
#[[plugins]]
#repo = 'tomasr/molokai'
#hook_add = '''
#let g:molokai_original = 1
#'''

#[[plugins]]
#repo = 'NLKNguyen/papercolor-theme'
#hook_add = '''
#set background=dark
#colorscheme PaperColor
#'''

#[[plugins]]
#repo = 'morhetz/gruvbox'
#hook_add = '''
#set background=dark
#autocmd vimenter * colorscheme gruvbox
#'''

#[[plugins]]
#repo = 'altercation/vim-colors-solarized'
#hook_add = '''
#au MyAutoCmd VimEnter * nested colorscheme solarized
#'''

[[plugins]]
repo = 'Mofiqul/dracula.nvim'
hook_add='''
colorscheme dracula
'''

#[[plugins]]
#repo = 'joshdick/onedark.vim'
#hook_add = '''
#"let g:airline_theme = 'onedark'
#set background=dark
#"au MyAutoCmd VimEnter * nested colorscheme onedark
#colorscheme onedark
#'''

#[[plugins]]
#repo = 'sonph/onehalf'
#hook_add = '''
#set background=dark
#"au MyAutoCmd VimEnter * nested colorscheme onehalfdark
#colorscheme onehalfdark
#'''
# }}}

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <leader>gg :Git<CR>
nnoremap <leader>gc :Git commit<CR>
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive']
depends = 'vim-airline-themes'
hook_source = '''
let g:airline#extentions#tabline#enabled = 1
let g:airline_theme = 'dracula'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#[[plugins]]
#repo = 'ervandew/supertab'
#hook_add = '''
#let g:SuperTabContextDefaultCompletionType = "context"
#let g:SuperTabDefaultCompletionType = "<c-n>"
#'''
#[[plugins]]
#repo = 'ctrlpvim/ctrlp.vim'

#[[plugins]]
#repo = 'scrooloose/nerdtree'
#hook_add = '''
#nnoremap <silent><C-e> :NERDTreeToggle<CR>
#'''

[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
nnoremap <silent><C-f> :Vaffle<CR>
nnoremap <leader>op :Vaffle<CR>
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'junegunn/fzf.vim'
