#[[plugins]]
#repo = 'tomasr/molokai'
#hook_add = '''
#let g:molokai_original = 1
#'''

#[[plugins]]
#repo = 'NLKNguyen/papercolor-theme'
#hook_add = '''
#set background=dark
#colorscheme PaperColor
#'''

#[[plugins]]
#repo = 'morhetz/gruvbox'
#hook_add = '''
#set background=dark
#autocmd vimenter * colorscheme gruvbox
#'''

#[[plugins]]
#repo = 'altercation/vim-colors-solarized'
#hook_add = '''
#au MyAutoCmd VimEnter * nested colorscheme solarized
#'''

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
"let g:airline_theme = 'onedark'
set background=dark
"au MyAutoCmd VimEnter * nested colorscheme onedark
colorscheme onedark
'''

#[[plugins]]
#repo = 'sonph/onehalf'
#hook_add = '''
#set background=dark
#"au MyAutoCmd VimEnter * nested colorscheme onehalfdark
#colorscheme onehalfdark
#'''

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive']
hook_add = '''
let g:airline#extentions#tabline#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
"let g:airline_theme = 'papercolor'
let g:airline_theme = 'onedark'
"let g:airline_theme = 'gruvbox'
'''

[[plugins]]
repo = 'ervandew/supertab'
hook_add = '''
let g:SuperTabContextDefaultCompletionType = "context"
let g:SuperTabDefaultCompletionType = "<c-n>"
'''
#[[plugins]]
#repo = 'ctrlpvim/ctrlp.vim'

#[[plugins]]
#repo = 'scrooloose/nerdtree'
#hook_add = '''
#nnoremap <silent><C-e> :NERDTreeToggle<CR>
#'''

[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
nnoremap <silent><C-f> :Vaffle<CR>
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

